url: http://kidlj.com
markdown: rdiscount
permalink: /blog/:year-:month-:day-:title.html
paginate: 10
paginate_path: "blog/page:num"
domain: kidlj.com
commits: https://github.com/kidlj/kidlj.github.io/commits/master/

defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "wikies"
    values:
      layout: "wiki"

collections:
  wikies:
    output: true
    permalink: /wiki/:path/
