url: http://kidlj.com
permalink: /t/:year-:month-:day-:title.html
gems: [jekyll-paginate]
paginate: 10 
paginate_path: "page:num"
domain: kidlj.com
commits: https://github.com/kidlj/kidlj.github.io/commits/master/


defaults:

- scope: 
    path: ""
    type: "posts"
  values:
    layout: "post"

- scope:
    path: ""
    type: "wikies"
  values:
    layout: "wiki"

- scope:
    path: ""
    type: "wagtail"
  values:
    layout: "howto"

collections:
  wikies:
    output: true
    permalink: /wiki/:name.html
  wagtail:
    output: true
    permalink: /wagtail/:path/
