url: http://kidlj.com
markdown: rdiscount
pygments: false
permalink: /expr/:year-:month-:day-:title.html
paginate: 30
paginate_path: "expr/page:num"
domain: kidlj.com
google_analytics: UA-46286887-1



