url: http://kidlj.com
markdown: rdiscount
pygments: false
permalink: /blog/:year-:month-:day-:title.html
paginate: 10
paginate_path: "blog/page:num"
domain: kidlj.com
google_analytics: UA-46286887-1


