url: http://www.ideavirgin.com
markdown: rdiscount
pygments: false
permalink: /expr/:year-:month-:day-:title.html
paginate: 30
paginate_path: "expr/page:num"
disqus_shortname: ideavirgin
domain: ideavirgin.com
google_analytics: UA-46286887-1



